service: engster-nuxt

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-northeast-2

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-plugin-warmup

custom:
  apigwBinary:
    types:
      - "*/*"
  customDomain:
    domainName: engster.co.kr
    basePath: ""
    stage: prod
    createRoute53Record: true
  warmup:
    default:
      enabled: true
      events:
        - schedule: "cron(0/5 7-23 ? * MON-SUN *)"
        - schedule: "cron(0/5 0-2 ? * MON-SUN *)"
      concurrency: 1

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}
